import React from "react";
import ReactFullpage from "@fullpage/react-fullpage";
import AboutSection from "../Containers/About";
import MainSection from "../Containers/MainSection";
import NewsSection from "../Containers/NewsSection";
import Head from "next/head";

const Fullpage = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <ReactFullpage
      scrollingSpeed={1000} /* Options here */
      render={({ state, fullpageApi }) => {
        console.log(state, "state");
        return (
          <ReactFullpage.Wrapper>
            <MainSection />
            <AboutSection />
            <NewsSection />
          </ReactFullpage.Wrapper>
        );
      }}
    />
  </>
);

export default Fullpage;
