import Head from "next/head";
import { Box } from "@mui/material";
import { useRouter } from "next/router";
import BgSwipeBox from "../components/BgSwipeBox";

export default function Home() {
  let router = useRouter();

  // router.push("/Home")
  const mainImages = [
    "https://media.gettyimages.com/photos/hazrat-imam-mosque-in-tashkent-uzbekistan-picture-id1190727660?s=612x612",
  ];

  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          type="text/javascript"
          src="vendors/scrolloverflow.min.js"
        ></script>
        <link rel="stylesheet" type="text/css" href="fullpage.css" />
        <script src="vendors/easings.min.js"></script>
        <script type="text/javascript" src="fullpage.js"></script>
      </Head>

      <Box component={"main"}>
        <Box sx={{ width: "100%", height: "100vh" }}>
          <BgSwipeBox images={mainImages}>nega</BgSwipeBox>
        </Box>
      </Box>
    </Box>
  );
}
