import React from "react";
import ReactFullpage from "@fullpage/react-fullpage";
import AboutSection from "../Containers/About";
import MainSection from "../Containers/MainSection";
import Head from "next/head";
import Company from "../Containers/Company";
import News from "../Containers/NewsSection";

const Fullpage = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link
        rel="stylesheet"
        href="https://video-react.github.io/assets/video-react.css"
      />
    </Head>
    <ReactFullpage
      scrollingSpeed={1000} /* Options here */
      render={({ state, fullpageApi }) => {
        console.log(state, "state");
        return (
          <ReactFullpage.Wrapper>
            <MainSection />
            <AboutSection />
            <News />
            <Company />
          </ReactFullpage.Wrapper>
        );
      }}
    />
  </>
);

export default Fullpage;
